<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="5.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Internative.FoodRecipes.Domain\Internative.FoodRecipes.Domain.csproj" />
  </ItemGroup>

</Project>
