<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>FoodRecipes.Services</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.13.1" />
    <PackageReference Include="MaxMind.GeoIP2" Version="4.0.1" />
    <PackageReference Include="iTextSharp.LGPLv2.Core" Version="1.7.0" />
    <PackageReference Include="MailKit" Version="2.10.1" />
    <PackageReference Include="SkiaSharp" Version="2.80.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.2" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.2.8" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoodRecipes.Core\FoodRecipes.Core.csproj" />
    <ProjectReference Include="..\FoodRecipes.Data\FoodRecipes.Data.csproj" />
  </ItemGroup>

</Project>
